### ISSUE TITLE
Cannot get download working

### ISSUE THREAD

**Issue by eedrah** [garethflowers/atom-portable#13]
Unfortunately I cannot get this download working - it appears clicking the links from the gh-pages site downloads the zip/tar balls, but running the exe that is supplied does not work. The atom exe is not included.

If I am missing a step it would be nice to have the instructions on the page.

Thanks

**Comment by eedrah** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9520856/17164506/1d55904a-5386-11e6-9ecf-e2cc1e2a6685.png)
Unpacking the zip and then running the exe gives the above

**Comment by eedrah** [comment]
For those who are coming here with the same problem, I found a link to the packaged portable apps versions here:
https://sourceforge.net/projects/atomportable/

**Comment by eedrah** [comment]
See pull request #14

**Comment by KrisZane** [comment]
Code in repositories often require a 3rd party tool to in some way run or compile them, which is why there is a releases tab on most projects: https://github.com/garethflowers/atom-portable/releases :)

**Comment by eedrah** [comment]
Not new, just tired and incompetent - completely forgot about releases and should have linked there rather than SourceForge.

I think the point still stands though, does it not? There should be a link from the gh-pages site to the releases, rather than the zip/tarballs of the code?

**Comment by KrisZane** [comment]
That is of course an entirely different question, I've heard pro's and con's for linking to software releases, but never really seen anyone come to a definite conclusion on this one. :P

In my personal opinion though, the releases tab is right there on the front page and even says if it has releases or not, so I don't know if it is entirely necessary to add another link to the front page. This is of course entirely an issue of knowledge sharing, of people knowing or no knowing that there is a releases tab.

![1469599734](https://cloud.githubusercontent.com/assets/12501838/17165562/84a1e6fe-53d1-11e6-9342-780599e863ca.png)

**Comment by eedrah** [comment]
Great points. And an interesting debate for github READMEs - I'm not sure what I think. I was thinking less about github though, and more about the consumer site for non-coders - http://gareth.flowers/atom-portable/

It looks like it is auto-generated from the README and doesn't include a link to the releases, so one needs to put the download link in the README for it to show up there. 

(Of course, my pull request doesn't actually fix the gh-pages site - it will need to be regenerated. But a step in that direction at least)

Thanks for the correction on the releases :)

**Comment by KrisZane** [comment]
No problem. :)

I think the buttons on that site must somehow be changeable, as they are kind of very specific, so I think it would help if the download buttons actually just linked to the files in the release section instead? :P

I just think that people might miss the link regardless and still click the download buttons and get the code repository instead.

Edit: Never mind, it seems the auto generated pages are only capable of doing one specific thing and are not changeable at all.
