### ISSUE TITLE
Proxy Settings

### ISSUE THREAD

**Issue by maltedudd** [garethflowers/atom-portable#18]
Hi, 

for implementing my prox-configuration i need to change the .apmrc 
Unfortunately it is always overritten, when i change the file in /Data/atom/.apm.

A .apmrc in Users-Folder of Windows does not exists for portable version. Where can i change my settings? 

Greetings
Malte

**Comment by relief-melone** [comment]
Having the same problem. Solution for this one would be great as I think alot of users who are in need of the portable version will also have to set the proxy settings

**Comment by garethflowers** [comment]
The local `%APPDATA%\.atom` directory is redirected to `\Data\atom`by the portable application. You can therefore create a `.apmrc` file in the data directory (i.e. **`\Data\atom\.apmrc`**) and it should work the same as creating it the users home directory.

**Comment by bigme666** [comment]
> The local `%APPDATA%\.atom` directory is redirected to `\Data\atom`by the portable application. You can therefore create a `.apmrc` file in the data directory (i.e. **`\Data\atom\.apmrc`**) and it should work the same as creating it the users home directory.

This hint worked for me
