### ISSUE TITLE
Please, update to Atom 1.17

### ISSUE THREAD

**Issue by gusbemacbe** [garethflowers/atom-portable#19]
Atom 1.13 is outdated. Atom released the official version 1.17.

**Comment by underwoodblog** [comment]
You can do it by yourself with replacing the files in App/Atom with newer ones. Worked for me to update to 1.15.

**Comment by gusbemacbe** [comment]
I copied and it worked, but it crashed a lot.

**Comment by underwoodblog** [comment]
I have updated to 1.17. Haven't used it often but it works stable. Have you updated all plugins?

**Comment by gusbemacbe** [comment]
Yes, I did, but it was still crashing. I believe because I was using a USB drive.

**Comment by underwoodblog** [comment]
Yes, that is possible, I'm running it on a build in HDD.

**Comment by gusbemacbe** [comment]
Would it be quick on a SD in place of USB drive (extern HD)?

**Comment by underwoodblog** [comment]
Maby with a USB 3.0 SSD. Isn't very fast from the internal SATA-Drive (HDD, no SSD).

Have you tryed a other (faster) USB-Stick? Maby yours has an error. You can check it with H2testw but this deletes all data on it.

**Comment by gusbemacbe** [comment]
Check my USB drive's photo:

![image](https://cloud.githubusercontent.com/assets/2257024/26506568/8124115a-4223-11e7-829f-779cabfa0d1d.png)

You confused me. Is it an USB drive or an USB Stick?

**Comment by underwoodblog** [comment]
This is an USB-Stick and it looks like a cheap (slow) USB 2.0. 

_**I'm running it from my internal SATA Hard-Disk-Drive and it still starts slow.**_

**Comment by gusbemacbe** [comment]
Ah, too bad, how do I know if my external HD WD My Passport is 2.0 or 3.0?

**Comment by underwoodblog** [comment]
Mostly USB 3.0 jacks and plugs are blue. Search google for pictures of USB 3.0 ports and cables.

**Comment by lemuelmc** [comment]
Any updates for 1.17 ?
I know you can just go ahead and copy it to Atom folder but doing so will result in unintended behavior. Like Atom can no longer list available packages or check for any updates:

`tunneling socket could not be established, statusCode=407`

Just to iterate, manually updating Atom by copy-pasting it to Atom folder will break Atom Package Manager.

**Comment by gusbemacbe** [comment]
@lemuelmc, copy the similar files to Atom Portable's files. Do not copy the files which are not similar to Atom files. 

If you really 1.17, let me update my files for you.

**Comment by underwoodblog** [comment]
I have updated to 1.17.2 without problems. I only had to reinstall atom-buitify but this is a known issue. Atom Package Manager works to.

**Comment by garethflowers** [comment]
Sorry for the delay - [v1.17.2](https://github.com/garethflowers/atom-portable/releases/tag/v1.17.2)

**Comment by lemuelmc** [comment]
@garethflowers 
Big thanks!
