### ISSUE TITLE
Incorrect license listed in readme

### ISSUE THREAD

**Issue by JohnTHaller** [garethflowers/atom-portable#24]
In the readme, it states:

> Portable application code released under the MIT license.

The PortableApps.com Launcher is licensed under the GPL and can not be re-licensed under MIT.

**Comment by garethflowers** [comment]
It's not very clear to find on the PortableApps.com, but I'm assuming that it would be [GPL v3.0](https://choosealicense.com/licenses/gpl-3.0/)?

**Comment by JohnTHaller** [comment]
It's GPL 2.0.  The license for the launcher is correctly included in your package (Other\Source\LauncherLicense.txt)

**Comment by garethflowers** [comment]
Thanks for the clarification - resolved by 5f92ba424edabe52e130124d9be8a5b006348def.
