### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by slomp** [garethflowers/atom-portable#9]
Hi there,

I am having trouble running the recently updated Atom Portable 1.6.x (I have tried to run it on Windows 7 x64 and on Windows 10 x64).

When I attempt to launch it, I get a JavaScript error message related to the `atom.asar` file (screenshot below).

![atom-portable-error](https://cloud.githubusercontent.com/assets/526886/14236927/bbf2e096-fa57-11e5-88a8-5ee72afd6fbe.png)

**Comment by garethflowers** [comment]
Please ensure you are using the **.paf.exe** installer from the [latest release](https://github.com/garethflowers/atom-portable/releases/latest).

From version 1.6 onwards Atom Portable uses some large binaries (which require [LFS](https://git-lfs.github.com/)) and are not included in any of the zip file downloads.

**Comment by slomp** [comment]
Thanks for the feedback.

As you suggested, running the installer does get rid of the problem.

I have been using Atom portable via a series of symlinks (junctions) and batch scripts (for things like setting up ATOM_HOME prior to launching it) so that all members of the team can get instant updates of the editor when they update their working tree.

~~I will automate the LFS pull into my local team setup.~~

I forgot that I already had git lfs installed in the repository-maintenance machine; just had to add a `git lfs fetch` and `git lfs checkout .` to my update script in order to the retrieve the files.
